apiVersion: apps/v1
kind: Deployment
metadata:
  name: architecture-center-backend-ms
  namespace: architecture-center-api-dev
  labels:
    app: architecture-center-backend-ms
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: architecture-center-backend-ms
      version: v1
  template:
    metadata:
      labels:
        app: architecture-center-backend-ms
        version: v1
    spec:
      containers:
      - name: architecture-center-backend-ms
        image: ms.io:5000/architecture-center/backend:1.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/src/app/.env
            name: env
            subPath: .env
      volumes:
      - configMap:
          defaultMode: 420
          name: app-params
        name: env
#       livenessProbe:
#         httpGet:
#           path: /actuator/health
#           port: 8989
#         initialDelaySeconds: 3
#       readinessProbe:
#         httpGet:
#           path: /actuator/health
#           port: 8989
#         initialDelaySeconds: 3
#         periodSeconds: 3
#        resources:
#          requests:
#            memory: "256Mi"
#            cpu: "1"
#          limits:
#            memory: "256Mi"
#            cpu: "1"